name: ai-resume-parser
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - spacy>=3.5
    - pdfplumber>=0.7.6
    - python-docx>=0.8.11
    - pytesseract>=0.3.10
    - pillow>=9.0
    - transformers>=4.30
    - sentence-transformers>=2.2
    - PyPDF2>=3.0
    - regex
    - pydantic
    - click
    - pytest
    - uvicorn
    - fastapi
    - python-multipart
    - scikit-learn
    - pandas
    - openpyxl
